
package org.apache.ode.pmapi;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.9
 * 2018-01-08T22:45:26.518+01:00
 * Generated source version: 3.0.9
 */

@WebFault(name = "ManagementFault", targetNamespace = "http://www.apache.org/ode/pmapi")
public class GetSnapshotVariablesFault extends Exception {
    
    private java.lang.String managementFault;

    public GetSnapshotVariablesFault() {
        super();
    }
    
    public GetSnapshotVariablesFault(String message) {
        super(message);
    }
    
    public GetSnapshotVariablesFault(String message, Throwable cause) {
        super(message, cause);
    }

    public GetSnapshotVariablesFault(String message, java.lang.String managementFault) {
        super(message);
        this.managementFault = managementFault;
    }

    public GetSnapshotVariablesFault(String message, java.lang.String managementFault, Throwable cause) {
        super(message, cause);
        this.managementFault = managementFault;
    }

    public java.lang.String getFaultInfo() {
        return this.managementFault;
    }
}
