
package org.apache.ode.pmapi;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.9
 * 2017-10-23T12:01:31.132+02:00
 * Generated source version: 3.0.9
 */

@WebFault(name = "ManagementFault", targetNamespace = "http://www.apache.org/ode/pmapi")
public class GetSnapshotPartnerLinksFault extends Exception {
    
    private java.lang.String managementFault;

    public GetSnapshotPartnerLinksFault() {
        super();
    }
    
    public GetSnapshotPartnerLinksFault(String message) {
        super(message);
    }
    
    public GetSnapshotPartnerLinksFault(String message, Throwable cause) {
        super(message, cause);
    }

    public GetSnapshotPartnerLinksFault(String message, java.lang.String managementFault) {
        super(message);
        this.managementFault = managementFault;
    }

    public GetSnapshotPartnerLinksFault(String message, java.lang.String managementFault, Throwable cause) {
        super(message, cause);
        this.managementFault = managementFault;
    }

    public java.lang.String getFaultInfo() {
        return this.managementFault;
    }
}
