package org.apache.ode.pmapi;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.9
 * 2018-01-08T22:45:26.534+01:00
 * Generated source version: 3.0.9
 * 
 */
@WebService(targetNamespace = "http://www.apache.org/ode/pmapi", name = "InstanceManagementPortType")
@XmlSeeAlso({ObjectFactory.class, org.apache.ode.pmapi.types._2006._08._02.ObjectFactory.class})
public interface InstanceManagementPortType {

    @WebResult(name = "instance-info", targetNamespace = "")
    @Action(input = "http://www.apache.org/ode/pmapi/InstanceManagementPortType/jumpToActivityRequest", output = "http://www.apache.org/ode/pmapi/InstanceManagementPortType/jumpToActivityResponse", fault = {@FaultAction(className = ManagementFault.class, value = "urn:jumpToActivitymanagementFault")})
    @RequestWrapper(localName = "jumpToActivity", targetNamespace = "http://www.apache.org/ode/pmapi", className = "org.apache.ode.pmapi.JumpToActivity")
    @WebMethod
    @ResponseWrapper(localName = "jumpToActivityResponse", targetNamespace = "http://www.apache.org/ode/pmapi", className = "org.apache.ode.pmapi.JumpToActivityResponse")
    public org.apache.ode.pmapi.types._2006._08._02.TInstanceInfo jumpToActivity(
        @WebParam(name = "iid", targetNamespace = "")
        long iid,
        @WebParam(name = "xpath", targetNamespace = "")
        java.lang.String xpath
    ) throws ManagementFault;

    @WebResult(name = "instance-info-list", targetNamespace = "")
    @Action(input = "http://www.apache.org/ode/pmapi/InstanceManagementPortType/listAllInstancesWithLimitRequest", output = "http://www.apache.org/ode/pmapi/InstanceManagementPortType/listAllInstancesWithLimitResponse", fault = {@FaultAction(className = ManagementFault.class, value = "urn:listAllInstancesWithLimitmanagementFault")})
    @RequestWrapper(localName = "listAllInstancesWithLimit", targetNamespace = "http://www.apache.org/ode/pmapi", className = "org.apache.ode.pmapi.ListAllInstancesWithLimit")
    @WebMethod
    @ResponseWrapper(localName = "listAllInstancesWithLimitResponse", targetNamespace = "http://www.apache.org/ode/pmapi", className = "org.apache.ode.pmapi.ListAllInstancesWithLimitResponse")
    public org.apache.ode.pmapi.types._2006._08._02.TInstanceInfoList listAllInstancesWithLimit(
        @WebParam(name = "payload", targetNamespace = "")
        int payload
    ) throws ManagementFault;

    @WebResult(name = "snapshot-info-list", targetNamespace = "")
    @Action(input = "http://www.apache.org/ode/pmapi/InstanceManagementPortType/getSnapshotsRequest", output = "http://www.apache.org/ode/pmapi/InstanceManagementPortType/getSnapshotsResponse", fault = {@FaultAction(className = ManagementFault.class, value = "urn:getSnapshotsmanagementFault")})
    @RequestWrapper(localName = "getSnapshots", targetNamespace = "http://www.apache.org/ode/pmapi", className = "org.apache.ode.pmapi.GetSnapshots")
    @WebMethod
    @ResponseWrapper(localName = "getSnapshotsResponse", targetNamespace = "http://www.apache.org/ode/pmapi", className = "org.apache.ode.pmapi.GetSnapshotsResponse")
    public org.apache.ode.pmapi.types._2006._08._02.TSnapshotInfoList getSnapshots(
        @WebParam(name = "iid", targetNamespace = "")
        long iid,
        @WebParam(name = "activityXPath", targetNamespace = "")
        java.lang.String activityXPath
    ) throws ManagementFault;

    @WebResult(name = "instance-info-list", targetNamespace = "")
    @Action(input = "http://www.apache.org/ode/pmapi/InstanceManagementPortType/listInstancesRequest", output = "http://www.apache.org/ode/pmapi/InstanceManagementPortType/listInstancesResponse", fault = {@FaultAction(className = ManagementFault.class, value = "urn:listInstancesmanagementFault")})
    @RequestWrapper(localName = "listInstances", targetNamespace = "http://www.apache.org/ode/pmapi", className = "org.apache.ode.pmapi.ListInstances")
    @WebMethod
    @ResponseWrapper(localName = "listInstancesResponse", targetNamespace = "http://www.apache.org/ode/pmapi", className = "org.apache.ode.pmapi.ListInstancesResponse")
    public org.apache.ode.pmapi.types._2006._08._02.TInstanceInfoList listInstances(
        @WebParam(name = "filter", targetNamespace = "")
        java.lang.String filter,
        @WebParam(name = "order", targetNamespace = "")
        java.lang.String order,
        @WebParam(name = "limit", targetNamespace = "")
        int limit
    ) throws ManagementFault;

    @WebResult(name = "variable-info", targetNamespace = "")
    @Action(input = "http://www.apache.org/ode/pmapi/InstanceManagementPortType/getVariableInfoRequest", output = "http://www.apache.org/ode/pmapi/InstanceManagementPortType/getVariableInfoResponse", fault = {@FaultAction(className = ManagementFault.class, value = "urn:getVariableInfomanagementFault")})
    @RequestWrapper(localName = "getVariableInfo", targetNamespace = "http://www.apache.org/ode/pmapi", className = "org.apache.ode.pmapi.GetVariableInfo")
    @WebMethod
    @ResponseWrapper(localName = "getVariableInfoResponse", targetNamespace = "http://www.apache.org/ode/pmapi", className = "org.apache.ode.pmapi.GetVariableInfoResponse")
    public org.apache.ode.pmapi.types._2006._08._02.TVariableInfo getVariableInfo(
        @WebParam(name = "sid", targetNamespace = "")
        java.lang.String sid,
        @WebParam(name = "varName", targetNamespace = "")
        java.lang.String varName
    ) throws ManagementFault;

    @WebResult(name = "instance-info", targetNamespace = "")
    @Action(input = "http://www.apache.org/ode/pmapi/InstanceManagementPortType/recoverActivityRequest", output = "http://www.apache.org/ode/pmapi/InstanceManagementPortType/recoverActivityResponse", fault = {@FaultAction(className = ManagementFault.class, value = "urn:recoverActivitymanagementFault")})
    @RequestWrapper(localName = "recoverActivity", targetNamespace = "http://www.apache.org/ode/pmapi", className = "org.apache.ode.pmapi.RecoverActivity")
    @WebMethod
    @ResponseWrapper(localName = "recoverActivityResponse", targetNamespace = "http://www.apache.org/ode/pmapi", className = "org.apache.ode.pmapi.RecoverActivityResponse")
    public org.apache.ode.pmapi.types._2006._08._02.TInstanceInfo recoverActivity(
        @WebParam(name = "iid", targetNamespace = "")
        long iid,
        @WebParam(name = "aid", targetNamespace = "")
        long aid,
        @WebParam(name = "action", targetNamespace = "")
        java.lang.String action
    ) throws ManagementFault;

    @WebResult(name = "scope-info", targetNamespace = "")
    @Action(input = "http://www.apache.org/ode/pmapi/InstanceManagementPortType/getScopeInfoWithActivityRequest", output = "http://www.apache.org/ode/pmapi/InstanceManagementPortType/getScopeInfoWithActivityResponse", fault = {@FaultAction(className = ManagementFault.class, value = "urn:getScopeInfoWithActivitymanagementFault")})
    @RequestWrapper(localName = "getScopeInfoWithActivity", targetNamespace = "http://www.apache.org/ode/pmapi", className = "org.apache.ode.pmapi.GetScopeInfoWithActivity")
    @WebMethod
    @ResponseWrapper(localName = "getScopeInfoWithActivityResponse", targetNamespace = "http://www.apache.org/ode/pmapi", className = "org.apache.ode.pmapi.GetScopeInfoWithActivityResponse")
    public org.apache.ode.pmapi.types._2006._08._02.TScopeInfo getScopeInfoWithActivity(
        @WebParam(name = "sid", targetNamespace = "")
        long sid,
        @WebParam(name = "activityInfo", targetNamespace = "")
        boolean activityInfo
    ) throws ManagementFault;

    @WebResult(name = "scope-info", targetNamespace = "")
    @Action(input = "http://www.apache.org/ode/pmapi/InstanceManagementPortType/getScopeInfoRequest", output = "http://www.apache.org/ode/pmapi/InstanceManagementPortType/getScopeInfoResponse", fault = {@FaultAction(className = ManagementFault.class, value = "urn:getScopeInfomanagementFault")})
    @RequestWrapper(localName = "getScopeInfo", targetNamespace = "http://www.apache.org/ode/pmapi", className = "org.apache.ode.pmapi.GetScopeInfo")
    @WebMethod
    @ResponseWrapper(localName = "getScopeInfoResponse", targetNamespace = "http://www.apache.org/ode/pmapi", className = "org.apache.ode.pmapi.GetScopeInfoResponse")
    public org.apache.ode.pmapi.types._2006._08._02.TScopeInfo getScopeInfo(
        @WebParam(name = "siid", targetNamespace = "")
        long siid
    ) throws ManagementFault;

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @Action(input = "http://www.apache.org/ode/pmapi/InstanceManagementPortType/resetAndTerminateRequest", output = "http://www.apache.org/ode/pmapi/InstanceManagementPortType/resetAndTerminateResponse", fault = {@FaultAction(className = ManagementFault.class, value = "urn:resetAndTerminatemanagementFault")})
    @WebMethod
    public void resetAndTerminate() throws ManagementFault;

    @WebResult(name = "instance-info", targetNamespace = "")
    @Action(input = "http://www.apache.org/ode/pmapi/InstanceManagementPortType/resumeRequest", output = "http://www.apache.org/ode/pmapi/InstanceManagementPortType/resumeResponse", fault = {@FaultAction(className = ManagementFault.class, value = "urn:resumemanagementFault")})
    @RequestWrapper(localName = "resume", targetNamespace = "http://www.apache.org/ode/pmapi", className = "org.apache.ode.pmapi.Resume")
    @WebMethod
    @ResponseWrapper(localName = "resumeResponse", targetNamespace = "http://www.apache.org/ode/pmapi", className = "org.apache.ode.pmapi.ResumeResponse")
    public org.apache.ode.pmapi.types._2006._08._02.TInstanceInfo resume(
        @WebParam(name = "iid", targetNamespace = "")
        long iid
    ) throws ManagementFault;

    @WebResult(name = "replayResponse", targetNamespace = "")
    @Action(input = "http://www.apache.org/ode/pmapi/InstanceManagementPortType/replayRequest", output = "http://www.apache.org/ode/pmapi/InstanceManagementPortType/replayResponse", fault = {@FaultAction(className = ManagementFault.class, value = "urn:replaymanagementFault")})
    @RequestWrapper(localName = "replay", targetNamespace = "http://www.apache.org/ode/pmapi", className = "org.apache.ode.pmapi.Replay")
    @WebMethod
    @ResponseWrapper(localName = "replayResponse", targetNamespace = "http://www.apache.org/ode/pmapi", className = "org.apache.ode.pmapi.ReplayResponse")
    public org.apache.ode.pmapi.types._2006._08._02.ReplayResponse replay(
        @WebParam(name = "replay", targetNamespace = "")
        org.apache.ode.pmapi.types._2006._08._02.Replay replay
    ) throws ManagementFault;

    @WebResult(name = "instance-info", targetNamespace = "")
    @Action(input = "http://www.apache.org/ode/pmapi/InstanceManagementPortType/getInstanceInfoRequest", output = "http://www.apache.org/ode/pmapi/InstanceManagementPortType/getInstanceInfoResponse", fault = {@FaultAction(className = ManagementFault.class, value = "urn:getInstanceInfomanagementFault")})
    @RequestWrapper(localName = "getInstanceInfo", targetNamespace = "http://www.apache.org/ode/pmapi", className = "org.apache.ode.pmapi.GetInstanceInfo")
    @WebMethod
    @ResponseWrapper(localName = "getInstanceInfoResponse", targetNamespace = "http://www.apache.org/ode/pmapi", className = "org.apache.ode.pmapi.GetInstanceInfoResponse")
    public org.apache.ode.pmapi.types._2006._08._02.TInstanceInfo getInstanceInfo(
        @WebParam(name = "iid", targetNamespace = "")
        long iid
    ) throws ManagementFault;

    @WebResult(name = "instance-info", targetNamespace = "")
    @Action(input = "http://www.apache.org/ode/pmapi/InstanceManagementPortType/finishRequest", output = "http://www.apache.org/ode/pmapi/InstanceManagementPortType/finishResponse", fault = {@FaultAction(className = ManagementFault.class, value = "urn:finishmanagementFault")})
    @RequestWrapper(localName = "finish", targetNamespace = "http://www.apache.org/ode/pmapi", className = "org.apache.ode.pmapi.Finish")
    @WebMethod
    @ResponseWrapper(localName = "finishResponse", targetNamespace = "http://www.apache.org/ode/pmapi", className = "org.apache.ode.pmapi.FinishResponse")
    public org.apache.ode.pmapi.types._2006._08._02.TInstanceInfo finish(
        @WebParam(name = "iid", targetNamespace = "")
        long iid
    ) throws ManagementFault;

    @WebResult(name = "instance-info-list", targetNamespace = "")
    @Action(input = "http://www.apache.org/ode/pmapi/InstanceManagementPortType/queryInstancesRequest", output = "http://www.apache.org/ode/pmapi/InstanceManagementPortType/queryInstancesResponse", fault = {@FaultAction(className = ManagementFault.class, value = "urn:queryInstancesmanagementFault")})
    @RequestWrapper(localName = "queryInstances", targetNamespace = "http://www.apache.org/ode/pmapi", className = "org.apache.ode.pmapi.QueryInstances")
    @WebMethod
    @ResponseWrapper(localName = "queryInstancesResponse", targetNamespace = "http://www.apache.org/ode/pmapi", className = "org.apache.ode.pmapi.QueryInstancesResponse")
    public org.apache.ode.pmapi.types._2006._08._02.TInstanceInfoList queryInstances(
        @WebParam(name = "payload", targetNamespace = "")
        java.lang.String payload
    ) throws ManagementFault;

    @WebResult(name = "bpel-event-list", targetNamespace = "")
    @Action(input = "http://www.apache.org/ode/pmapi/InstanceManagementPortType/listEventsRequest", output = "http://www.apache.org/ode/pmapi/InstanceManagementPortType/listEventsResponse", fault = {@FaultAction(className = ManagementFault.class, value = "urn:listEventsmanagementFault")})
    @RequestWrapper(localName = "listEvents", targetNamespace = "http://www.apache.org/ode/pmapi", className = "org.apache.ode.pmapi.ListEvents")
    @WebMethod
    @ResponseWrapper(localName = "listEventsResponse", targetNamespace = "http://www.apache.org/ode/pmapi", className = "org.apache.ode.pmapi.ListEventsResponse")
    public org.apache.ode.pmapi.types._2006._08._02.TEventInfoList listEvents(
        @WebParam(name = "instanceFilter", targetNamespace = "")
        java.lang.String instanceFilter,
        @WebParam(name = "eventFilter", targetNamespace = "")
        java.lang.String eventFilter,
        @WebParam(name = "maxCount", targetNamespace = "")
        int maxCount
    ) throws ManagementFault;

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "iterateResponse", targetNamespace = "http://www.apache.org/ode/pmapi", partName = "parameters")
    @Action(input = "http://www.apache.org/ode/pmapi/InstanceManagementPortType/iterateRequest", output = "http://www.apache.org/ode/pmapi/InstanceManagementPortType/iterateResponse", fault = {@FaultAction(className = ManagementFault.class, value = "urn:iteratemanagementFault")})
    @WebMethod
    public IterateResponse iterate() throws ManagementFault;

    @WebResult(name = "instance-info", targetNamespace = "")
    @Action(input = "http://www.apache.org/ode/pmapi/InstanceManagementPortType/reexecuteExtRequest", output = "http://www.apache.org/ode/pmapi/InstanceManagementPortType/reexecuteExtResponse", fault = {@FaultAction(className = ManagementFault.class, value = "urn:reexecuteExtmanagementFault")})
    @RequestWrapper(localName = "reexecuteExt", targetNamespace = "http://www.apache.org/ode/pmapi", className = "org.apache.ode.pmapi.ReexecuteExt")
    @WebMethod
    @ResponseWrapper(localName = "reexecuteExtResponse", targetNamespace = "http://www.apache.org/ode/pmapi", className = "org.apache.ode.pmapi.ReexecuteExtResponse")
    public org.apache.ode.pmapi.types._2006._08._02.TInstanceInfo reexecuteExt(
        @WebParam(name = "iid", targetNamespace = "")
        long iid,
        @WebParam(name = "xpath", targetNamespace = "")
        java.lang.String xpath,
        @WebParam(name = "snapshotXPath", targetNamespace = "")
        java.lang.String snapshotXPath,
        @WebParam(name = "version", targetNamespace = "")
        long version,
        @WebParam(name = "variables", targetNamespace = "")
        org.apache.ode.pmapi.types._2006._08._02.TVariableRefList variables,
        @WebParam(name = "partnerLinks", targetNamespace = "")
        org.apache.ode.pmapi.types._2006._08._02.TPartnerLinkRefList partnerLinks
    ) throws ManagementFault;

    @WebResult(name = "instance-info", targetNamespace = "")
    @Action(input = "http://www.apache.org/ode/pmapi/InstanceManagementPortType/faultRequest", output = "http://www.apache.org/ode/pmapi/InstanceManagementPortType/faultResponse", fault = {@FaultAction(className = ManagementFault.class, value = "urn:faultmanagementFault")})
    @RequestWrapper(localName = "fault", targetNamespace = "http://www.apache.org/ode/pmapi", className = "org.apache.ode.pmapi.Fault")
    @WebMethod
    @ResponseWrapper(localName = "faultResponse", targetNamespace = "http://www.apache.org/ode/pmapi", className = "org.apache.ode.pmapi.FaultResponse")
    public org.apache.ode.pmapi.types._2006._08._02.TInstanceInfo fault(
        @WebParam(name = "iid", targetNamespace = "")
        long iid
    ) throws ManagementFault;

    @WebResult(name = "snapshot-partnerLinks", targetNamespace = "")
    @Action(input = "http://www.apache.org/ode/pmapi/getSnapshotPartnerLinks", output = "http://www.apache.org/ode/pmapi/InstanceManagementPortType/getSnapshotPartnerLinksResponse", fault = {@FaultAction(className = GetSnapshotPartnerLinksFault.class, value = "urn:getSnapshotPartnerLinksgetSnapshotPartnerLinksFault")})
    @RequestWrapper(localName = "getSnapshotPartnerLinks", targetNamespace = "http://www.apache.org/ode/pmapi", className = "org.apache.ode.pmapi.GetSnapshotPartnerLinks")
    @WebMethod(action = "http://www.apache.org/ode/pmapi/getSnapshotPartnerLinks")
    @ResponseWrapper(localName = "getSnapshotPartnerLinksResponse", targetNamespace = "http://www.apache.org/ode/pmapi", className = "org.apache.ode.pmapi.GetSnapshotPartnerLinksResponse")
    public org.apache.ode.pmapi.types._2006._08._02.TSnapshotPartnerLinks getSnapshotPartnerLinks(
        @WebParam(name = "iid", targetNamespace = "")
        long iid,
        @WebParam(name = "snapshotId", targetNamespace = "")
        long snapshotId
    ) throws GetSnapshotPartnerLinksFault;

    @WebResult(name = "instance-info", targetNamespace = "")
    @Action(input = "http://www.apache.org/ode/pmapi/InstanceManagementPortType/reexecuteRequest", output = "http://www.apache.org/ode/pmapi/InstanceManagementPortType/reexecuteResponse", fault = {@FaultAction(className = ManagementFault.class, value = "urn:reexecutemanagementFault")})
    @RequestWrapper(localName = "reexecute", targetNamespace = "http://www.apache.org/ode/pmapi", className = "org.apache.ode.pmapi.Reexecute")
    @WebMethod
    @ResponseWrapper(localName = "reexecuteResponse", targetNamespace = "http://www.apache.org/ode/pmapi", className = "org.apache.ode.pmapi.ReexecuteResponse")
    public org.apache.ode.pmapi.types._2006._08._02.TInstanceInfo reexecute(
        @WebParam(name = "iid", targetNamespace = "")
        long iid,
        @WebParam(name = "xpath", targetNamespace = "")
        java.lang.String xpath,
        @WebParam(name = "snapshotXPath", targetNamespace = "")
        java.lang.String snapshotXPath,
        @WebParam(name = "version", targetNamespace = "")
        long version
    ) throws ManagementFault;

    @WebResult(name = "snapshot-variables", targetNamespace = "")
    @Action(input = "http://www.apache.org/ode/pmapi/getSnapshotVariables", output = "http://www.apache.org/ode/pmapi/InstanceManagementPortType/getSnapshotVariablesResponse", fault = {@FaultAction(className = GetSnapshotVariablesFault.class, value = "urn:getSnapshotVariablesgetSnapshotVariablesFault")})
    @RequestWrapper(localName = "getSnapshotVariables", targetNamespace = "http://www.apache.org/ode/pmapi", className = "org.apache.ode.pmapi.GetSnapshotVariables")
    @WebMethod(action = "http://www.apache.org/ode/pmapi/getSnapshotVariables")
    @ResponseWrapper(localName = "getSnapshotVariablesResponse", targetNamespace = "http://www.apache.org/ode/pmapi", className = "org.apache.ode.pmapi.GetSnapshotVariablesResponse")
    public org.apache.ode.pmapi.types._2006._08._02.TSnapshotVariables getSnapshotVariables(
        @WebParam(name = "iid", targetNamespace = "")
        long iid,
        @WebParam(name = "snapshotId", targetNamespace = "")
        long snapshotId
    ) throws GetSnapshotVariablesFault;

    @WebResult(name = "list", targetNamespace = "")
    @Action(input = "http://www.apache.org/ode/pmapi/InstanceManagementPortType/deleteRequest", output = "http://www.apache.org/ode/pmapi/InstanceManagementPortType/deleteResponse", fault = {@FaultAction(className = ManagementFault.class, value = "urn:deletemanagementFault")})
    @RequestWrapper(localName = "delete", targetNamespace = "http://www.apache.org/ode/pmapi", className = "org.apache.ode.pmapi.Delete")
    @WebMethod
    @ResponseWrapper(localName = "deleteResponse", targetNamespace = "http://www.apache.org/ode/pmapi", className = "org.apache.ode.pmapi.DeleteResponse")
    public org.apache.ode.pmapi.ListType delete(
        @WebParam(name = "filter", targetNamespace = "")
        java.lang.String filter
    ) throws ManagementFault;

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @Action(input = "http://www.apache.org/ode/pmapi/InstanceManagementPortType/iterateExtRequest", output = "http://www.apache.org/ode/pmapi/InstanceManagementPortType/iterateExtResponse", fault = {@FaultAction(className = ManagementFault.class, value = "urn:iterateExtmanagementFault")})
    @WebMethod
    public void iterateExt(
        @WebParam(partName = "parameters", name = "iterateExt", targetNamespace = "http://www.apache.org/ode/pmapi")
        IterateExt parameters
    ) throws ManagementFault;

    @WebResult(name = "instance-info-list", targetNamespace = "")
    @Action(input = "http://www.apache.org/ode/pmapi/InstanceManagementPortType/listAllInstancesRequest", output = "http://www.apache.org/ode/pmapi/InstanceManagementPortType/listAllInstancesResponse", fault = {@FaultAction(className = ManagementFault.class, value = "urn:listAllInstancesmanagementFault")})
    @RequestWrapper(localName = "listAllInstances", targetNamespace = "http://www.apache.org/ode/pmapi", className = "org.apache.ode.pmapi.ListAllInstances")
    @WebMethod
    @ResponseWrapper(localName = "listAllInstancesResponse", targetNamespace = "http://www.apache.org/ode/pmapi", className = "org.apache.ode.pmapi.ListAllInstancesResponse")
    public org.apache.ode.pmapi.types._2006._08._02.TInstanceInfoList listAllInstances() throws ManagementFault;

    @WebResult(name = "instance-info", targetNamespace = "")
    @Action(input = "http://www.apache.org/ode/pmapi/InstanceManagementPortType/suspendRequest", output = "http://www.apache.org/ode/pmapi/InstanceManagementPortType/suspendResponse", fault = {@FaultAction(className = ManagementFault.class, value = "urn:suspendmanagementFault")})
    @RequestWrapper(localName = "suspend", targetNamespace = "http://www.apache.org/ode/pmapi", className = "org.apache.ode.pmapi.Suspend")
    @WebMethod
    @ResponseWrapper(localName = "suspendResponse", targetNamespace = "http://www.apache.org/ode/pmapi", className = "org.apache.ode.pmapi.SuspendResponse")
    public org.apache.ode.pmapi.types._2006._08._02.TInstanceInfo suspend(
        @WebParam(name = "iid", targetNamespace = "")
        long iid
    ) throws ManagementFault;

    @WebResult(name = "instance-info-list", targetNamespace = "")
    @Action(input = "http://www.apache.org/ode/pmapi/InstanceManagementPortType/listInstancesSummaryRequest", output = "http://www.apache.org/ode/pmapi/InstanceManagementPortType/listInstancesSummaryResponse", fault = {@FaultAction(className = ManagementFault.class, value = "urn:listInstancesSummarymanagementFault")})
    @RequestWrapper(localName = "listInstancesSummary", targetNamespace = "http://www.apache.org/ode/pmapi", className = "org.apache.ode.pmapi.ListInstancesSummary")
    @WebMethod
    @ResponseWrapper(localName = "listInstancesSummaryResponse", targetNamespace = "http://www.apache.org/ode/pmapi", className = "org.apache.ode.pmapi.ListInstancesSummaryResponse")
    public org.apache.ode.pmapi.types._2006._08._02.TInstanceInfoList listInstancesSummary(
        @WebParam(name = "filter", targetNamespace = "")
        java.lang.String filter,
        @WebParam(name = "order", targetNamespace = "")
        java.lang.String order,
        @WebParam(name = "limit", targetNamespace = "")
        int limit
    ) throws ManagementFault;

    @WebResult(name = "dates", targetNamespace = "")
    @Action(input = "http://www.apache.org/ode/pmapi/InstanceManagementPortType/getEventTimelineRequest", output = "http://www.apache.org/ode/pmapi/InstanceManagementPortType/getEventTimelineResponse", fault = {@FaultAction(className = ManagementFault.class, value = "urn:getEventTimelinemanagementFault")})
    @RequestWrapper(localName = "getEventTimeline", targetNamespace = "http://www.apache.org/ode/pmapi", className = "org.apache.ode.pmapi.GetEventTimeline")
    @WebMethod
    @ResponseWrapper(localName = "getEventTimelineResponse", targetNamespace = "http://www.apache.org/ode/pmapi", className = "org.apache.ode.pmapi.GetEventTimelineResponse")
    public org.apache.ode.pmapi.ListType getEventTimeline(
        @WebParam(name = "instanceFilter", targetNamespace = "")
        java.lang.String instanceFilter,
        @WebParam(name = "eventFilter", targetNamespace = "")
        java.lang.String eventFilter
    ) throws ManagementFault;

    @WebResult(name = "getCommunicationResponse", targetNamespace = "")
    @Action(input = "http://www.apache.org/ode/pmapi/InstanceManagementPortType/getCommunicationRequest", output = "http://www.apache.org/ode/pmapi/InstanceManagementPortType/getCommunicationResponse", fault = {@FaultAction(className = ManagementFault.class, value = "urn:getCommunicationmanagementFault")})
    @RequestWrapper(localName = "getCommunication", targetNamespace = "http://www.apache.org/ode/pmapi", className = "org.apache.ode.pmapi.GetCommunication")
    @WebMethod
    @ResponseWrapper(localName = "getCommunicationResponse", targetNamespace = "http://www.apache.org/ode/pmapi", className = "org.apache.ode.pmapi.GetCommunicationResponse")
    public org.apache.ode.pmapi.types._2006._08._02.GetCommunicationResponse getCommunication(
        @WebParam(name = "getCommunication", targetNamespace = "")
        org.apache.ode.pmapi.types._2006._08._02.GetCommunication getCommunication
    ) throws ManagementFault;

    @WebResult(name = "snapshot-info", targetNamespace = "")
    @Action(input = "http://www.apache.org/ode/pmapi/InstanceManagementPortType/getSnapshotVersionsRequest", output = "http://www.apache.org/ode/pmapi/InstanceManagementPortType/getSnapshotVersionsResponse", fault = {@FaultAction(className = ManagementFault.class, value = "urn:getSnapshotVersionsmanagementFault")})
    @RequestWrapper(localName = "getSnapshotVersions", targetNamespace = "http://www.apache.org/ode/pmapi", className = "org.apache.ode.pmapi.GetSnapshotVersions")
    @WebMethod
    @ResponseWrapper(localName = "getSnapshotVersionsResponse", targetNamespace = "http://www.apache.org/ode/pmapi", className = "org.apache.ode.pmapi.GetSnapshotVersionsResponse")
    public org.apache.ode.pmapi.types._2006._08._02.TSnapshotInfo getSnapshotVersions(
        @WebParam(name = "iid", targetNamespace = "")
        long iid,
        @WebParam(name = "activityXPath", targetNamespace = "")
        java.lang.String activityXPath
    ) throws ManagementFault;

    @WebResult(name = "partnerLink-info", targetNamespace = "")
    @Action(input = "http://www.apache.org/ode/pmapi/InstanceManagementPortType/getPartnerLinkInfoRequest", output = "http://www.apache.org/ode/pmapi/InstanceManagementPortType/getPartnerLinkInfoResponse", fault = {@FaultAction(className = ManagementFault.class, value = "urn:getPartnerLinkInfomanagementFault")})
    @RequestWrapper(localName = "getPartnerLinkInfo", targetNamespace = "http://www.apache.org/ode/pmapi", className = "org.apache.ode.pmapi.GetPartnerLinkInfo")
    @WebMethod
    @ResponseWrapper(localName = "getPartnerLinkInfoResponse", targetNamespace = "http://www.apache.org/ode/pmapi", className = "org.apache.ode.pmapi.GetPartnerLinkInfoResponse")
    public org.apache.ode.pmapi.types._2006._08._02.TPartnerLinkInfo getPartnerLinkInfo(
        @WebParam(name = "sid", targetNamespace = "")
        java.lang.String sid,
        @WebParam(name = "partnerLinkName", targetNamespace = "")
        java.lang.String partnerLinkName
    ) throws ManagementFault;

    @WebResult(name = "instance-info", targetNamespace = "")
    @Action(input = "http://www.apache.org/ode/pmapi/InstanceManagementPortType/terminateRequest", output = "http://www.apache.org/ode/pmapi/InstanceManagementPortType/terminateResponse", fault = {@FaultAction(className = ManagementFault.class, value = "urn:terminatemanagementFault")})
    @RequestWrapper(localName = "terminate", targetNamespace = "http://www.apache.org/ode/pmapi", className = "org.apache.ode.pmapi.Terminate")
    @WebMethod
    @ResponseWrapper(localName = "terminateResponse", targetNamespace = "http://www.apache.org/ode/pmapi", className = "org.apache.ode.pmapi.TerminateResponse")
    public org.apache.ode.pmapi.types._2006._08._02.TInstanceInfo terminate(
        @WebParam(name = "iid", targetNamespace = "")
        long iid
    ) throws ManagementFault;
}
