//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.08 at 10:45:27 PM MEZ 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://de.unistuttgart.iaas.chor.integration", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package de.unistuttgart.iaas.chor.integration.headers;
