//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.23 at 12:01:31 PM MESZ 
//


package de.unistuttgart.iaas.chor.messages;

import javax.xml.bind.annotation.adapters.XmlAdapter;
import javax.xml.namespace.QName;

public class Adapter3
    extends XmlAdapter<String, QName>
{


    public QName unmarshal(String value) {
        return (de.unistuttgart.iaas.chor.parser.QNameParser.parseQName(value));
    }

    public String marshal(QName value) {
        return (de.unistuttgart.iaas.chor.parser.QNameParser.printQName(value));
    }

}
