//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.23 at 12:01:31 PM MESZ 
//


package de.unistuttgart.iaas.chor.messages;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ChoreographyModelStatesType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ChoreographyModelStatesType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Choreography_Active"/>
 *     &lt;enumeration value="Choreography_Deployed"/>
 *     &lt;enumeration value="Choreography_Disabled"/>
 *     &lt;enumeration value="Choreography_Retired"/>
 *     &lt;enumeration value="Choreography_Undeployed"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ChoreographyModelStatesType", namespace = "http://www.example.org/choreography_model_states")
@XmlEnum
public enum ChoreographyModelStatesType {

    @XmlEnumValue("Choreography_Active")
    CHOREOGRAPHY_ACTIVE("Choreography_Active"),
    @XmlEnumValue("Choreography_Deployed")
    CHOREOGRAPHY_DEPLOYED("Choreography_Deployed"),
    @XmlEnumValue("Choreography_Disabled")
    CHOREOGRAPHY_DISABLED("Choreography_Disabled"),
    @XmlEnumValue("Choreography_Retired")
    CHOREOGRAPHY_RETIRED("Choreography_Retired"),
    @XmlEnumValue("Choreography_Undeployed")
    CHOREOGRAPHY_UNDEPLOYED("Choreography_Undeployed");
    private final String value;

    ChoreographyModelStatesType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ChoreographyModelStatesType fromValue(String v) {
        for (ChoreographyModelStatesType c: ChoreographyModelStatesType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
