//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.23 at 12:01:31 PM MESZ 
//


package de.unistuttgart.iaas.chor.messages;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="choreographyBundle" type="{http://www.example.org/choreography_deployment_message}choreographyBundleType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "choreographyBundle"
})
@XmlRootElement(name = "ChorDeploymentMessage", namespace = "http://www.example.org/choreography_deployment_message")
public class ChorDeploymentMessage {

    @XmlElement(namespace = "http://www.example.org/choreography_deployment_message", required = true)
    protected ChoreographyBundleType choreographyBundle;

    /**
     * Gets the value of the choreographyBundle property.
     * 
     * @return
     *     possible object is
     *     {@link ChoreographyBundleType }
     *     
     */
    public ChoreographyBundleType getChoreographyBundle() {
        return choreographyBundle;
    }

    /**
     * Sets the value of the choreographyBundle property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChoreographyBundleType }
     *     
     */
    public void setChoreographyBundle(ChoreographyBundleType value) {
        this.choreographyBundle = value;
    }

}
