//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.08 at 10:45:27 PM MEZ 
//


package de.unistuttgart.iaas.chor.messages;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="choreographyModelId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="instanceWaitingTime" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="startParticipants" type="{http://www.example.org/choreography_control_message}StartParticipantType" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "choreographyModelId",
    "instanceWaitingTime",
    "startParticipants"
})
@XmlRootElement(name = "ChorStartMessage", namespace = "http://www.example.org/choreography_control_message")
public class ChorStartMessage {

    @XmlElement(namespace = "http://www.example.org/choreography_control_message", required = true)
    protected String choreographyModelId;
    @XmlElement(namespace = "http://www.example.org/choreography_control_message")
    protected Long instanceWaitingTime;
    @XmlElement(namespace = "http://www.example.org/choreography_control_message", required = true)
    protected List<StartParticipantType> startParticipants;

    /**
     * Gets the value of the choreographyModelId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChoreographyModelId() {
        return choreographyModelId;
    }

    /**
     * Sets the value of the choreographyModelId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChoreographyModelId(String value) {
        this.choreographyModelId = value;
    }

    /**
     * Gets the value of the instanceWaitingTime property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getInstanceWaitingTime() {
        return instanceWaitingTime;
    }

    /**
     * Sets the value of the instanceWaitingTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setInstanceWaitingTime(Long value) {
        this.instanceWaitingTime = value;
    }

    /**
     * Gets the value of the startParticipants property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the startParticipants property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStartParticipants().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link StartParticipantType }
     * 
     * 
     */
    public List<StartParticipantType> getStartParticipants() {
        if (startParticipants == null) {
            startParticipants = new ArrayList<StartParticipantType>();
        }
        return this.startParticipants;
    }

}
