//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.08 at 10:45:27 PM MEZ 
//


package de.unistuttgart.iaas.chor.messages;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ChorModelType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ChorModelType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="choreographyModelID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="choreographyModelName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="choreographyModelState" type="{http://www.example.org/choreography_model_states}ChoreographyModelStatesType"/>
 *         &lt;element name="processModels" type="{http://www.example.org/choreography_model_information_message}ChorProcessModelsInformationType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ChorModelType", namespace = "http://www.example.org/choreography_model_information_message", propOrder = {
    "choreographyModelID",
    "choreographyModelName",
    "choreographyModelState",
    "processModels"
})
public class ChorModelType {

    @XmlElement(required = true)
    protected String choreographyModelID;
    @XmlElement(required = true)
    protected String choreographyModelName;
    @XmlElement(required = true)
    protected ChoreographyModelStatesType choreographyModelState;
    @XmlElement(required = true)
    protected ChorProcessModelsInformationType processModels;

    /**
     * Gets the value of the choreographyModelID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChoreographyModelID() {
        return choreographyModelID;
    }

    /**
     * Sets the value of the choreographyModelID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChoreographyModelID(String value) {
        this.choreographyModelID = value;
    }

    /**
     * Gets the value of the choreographyModelName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChoreographyModelName() {
        return choreographyModelName;
    }

    /**
     * Sets the value of the choreographyModelName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChoreographyModelName(String value) {
        this.choreographyModelName = value;
    }

    /**
     * Gets the value of the choreographyModelState property.
     * 
     * @return
     *     possible object is
     *     {@link ChoreographyModelStatesType }
     *     
     */
    public ChoreographyModelStatesType getChoreographyModelState() {
        return choreographyModelState;
    }

    /**
     * Sets the value of the choreographyModelState property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChoreographyModelStatesType }
     *     
     */
    public void setChoreographyModelState(ChoreographyModelStatesType value) {
        this.choreographyModelState = value;
    }

    /**
     * Gets the value of the processModels property.
     * 
     * @return
     *     possible object is
     *     {@link ChorProcessModelsInformationType }
     *     
     */
    public ChorProcessModelsInformationType getProcessModels() {
        return processModels;
    }

    /**
     * Sets the value of the processModels property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChorProcessModelsInformationType }
     *     
     */
    public void setProcessModels(ChorProcessModelsInformationType value) {
        this.processModels = value;
    }

}
