//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.23 at 12:01:31 PM MESZ 
//


package de.unistuttgart.iaas.chor.messages;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ChorProcessModelType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ChorProcessModelType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="processModelID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="processModelName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="processModelState" type="{http://www.example.org/process_model_states}ProcessModelStatesType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ChorProcessModelType", namespace = "http://www.example.org/choreography_model_information_message", propOrder = {
    "processModelID",
    "processModelName",
    "processModelState"
})
public class ChorProcessModelType {

    @XmlElement(required = true)
    protected String processModelID;
    @XmlElement(required = true)
    protected String processModelName;
    @XmlElement(required = true)
    protected ProcessModelStatesType processModelState;

    /**
     * Gets the value of the processModelID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProcessModelID() {
        return processModelID;
    }

    /**
     * Sets the value of the processModelID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProcessModelID(String value) {
        this.processModelID = value;
    }

    /**
     * Gets the value of the processModelName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProcessModelName() {
        return processModelName;
    }

    /**
     * Sets the value of the processModelName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProcessModelName(String value) {
        this.processModelName = value;
    }

    /**
     * Gets the value of the processModelState property.
     * 
     * @return
     *     possible object is
     *     {@link ProcessModelStatesType }
     *     
     */
    public ProcessModelStatesType getProcessModelState() {
        return processModelState;
    }

    /**
     * Sets the value of the processModelState property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProcessModelStatesType }
     *     
     */
    public void setProcessModelState(ProcessModelStatesType value) {
        this.processModelState = value;
    }

}
