//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.23 at 12:01:31 PM MESZ 
//


package de.unistuttgart.iaas.chor.messages;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="chorInstanceID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="processInstance" type="{http://www.example.org/choreography_instance_information_message}processInstanceHistoryOfChorInstance" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="messageLinkInstance" type="{http://www.example.org/choreography_instance_information_message}messageLinkInstanceInformation" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "chorInstanceID",
    "processInstance",
    "messageLinkInstance"
})
@XmlRootElement(name = "GetChorInstanceHistoryReturnMessage")
public class GetChorInstanceHistoryReturnMessage {

    @XmlElement(required = true)
    protected String chorInstanceID;
    protected List<ProcessInstanceHistoryOfChorInstance> processInstance;
    protected List<MessageLinkInstanceInformation> messageLinkInstance;

    /**
     * Gets the value of the chorInstanceID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChorInstanceID() {
        return chorInstanceID;
    }

    /**
     * Sets the value of the chorInstanceID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChorInstanceID(String value) {
        this.chorInstanceID = value;
    }

    /**
     * Gets the value of the processInstance property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the processInstance property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProcessInstance().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ProcessInstanceHistoryOfChorInstance }
     * 
     * 
     */
    public List<ProcessInstanceHistoryOfChorInstance> getProcessInstance() {
        if (processInstance == null) {
            processInstance = new ArrayList<ProcessInstanceHistoryOfChorInstance>();
        }
        return this.processInstance;
    }

    /**
     * Gets the value of the messageLinkInstance property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the messageLinkInstance property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMessageLinkInstance().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MessageLinkInstanceInformation }
     * 
     * 
     */
    public List<MessageLinkInstanceInformation> getMessageLinkInstance() {
        if (messageLinkInstance == null) {
            messageLinkInstance = new ArrayList<MessageLinkInstanceInformation>();
        }
        return this.messageLinkInstance;
    }

}
