//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.23 at 12:01:31 PM MESZ 
//


package de.unistuttgart.iaas.chor.messages;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="method" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="processInstanceID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="elementModelID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="activityXPath" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "method",
    "processInstanceID",
    "elementModelID",
    "activityXPath"
})
@XmlRootElement(name = "GetSnapshotsMessage")
public class GetSnapshotsMessage {

    @XmlElement(required = true)
    protected String method;
    @XmlElement(required = true)
    protected String processInstanceID;
    @XmlElement(required = true)
    protected String elementModelID;
    @XmlElement(required = true)
    protected String activityXPath;

    /**
     * Gets the value of the method property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMethod() {
        return method;
    }

    /**
     * Sets the value of the method property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMethod(String value) {
        this.method = value;
    }

    /**
     * Gets the value of the processInstanceID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProcessInstanceID() {
        return processInstanceID;
    }

    /**
     * Sets the value of the processInstanceID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProcessInstanceID(String value) {
        this.processInstanceID = value;
    }

    /**
     * Gets the value of the elementModelID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getElementModelID() {
        return elementModelID;
    }

    /**
     * Sets the value of the elementModelID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setElementModelID(String value) {
        this.elementModelID = value;
    }

    /**
     * Gets the value of the activityXPath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActivityXPath() {
        return activityXPath;
    }

    /**
     * Sets the value of the activityXPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActivityXPath(String value) {
        this.activityXPath = value;
    }

}
