//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.08 at 10:45:27 PM MEZ 
//


package de.unistuttgart.iaas.chor.messages;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for messageLinkInstanceInformation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="messageLinkInstanceInformation">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="choreographyInstanceID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="messageLinkInstanceID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="events" type="{http://www.example.org/choreography_instance_information_message}messageLinkInstanceEventType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "messageLinkInstanceInformation", propOrder = {
    "choreographyInstanceID",
    "messageLinkInstanceID",
    "events"
})
public class MessageLinkInstanceInformation {

    @XmlElement(required = true)
    protected String choreographyInstanceID;
    @XmlElement(required = true)
    protected String messageLinkInstanceID;
    protected List<MessageLinkInstanceEventType> events;

    /**
     * Gets the value of the choreographyInstanceID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChoreographyInstanceID() {
        return choreographyInstanceID;
    }

    /**
     * Sets the value of the choreographyInstanceID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChoreographyInstanceID(String value) {
        this.choreographyInstanceID = value;
    }

    /**
     * Gets the value of the messageLinkInstanceID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMessageLinkInstanceID() {
        return messageLinkInstanceID;
    }

    /**
     * Sets the value of the messageLinkInstanceID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMessageLinkInstanceID(String value) {
        this.messageLinkInstanceID = value;
    }

    /**
     * Gets the value of the events property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the events property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEvents().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MessageLinkInstanceEventType }
     * 
     * 
     */
    public List<MessageLinkInstanceEventType> getEvents() {
        if (events == null) {
            events = new ArrayList<MessageLinkInstanceEventType>();
        }
        return this.events;
    }

}
