//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.08 at 10:45:27 PM MEZ 
//


package de.unistuttgart.iaas.chor.messages;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the de.unistuttgart.iaas.chor.messages package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: de.unistuttgart.iaas.chor.messages
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link MessageLinkInstanceEventType }
     * 
     */
    public MessageLinkInstanceEventType createMessageLinkInstanceEventType() {
        return new MessageLinkInstanceEventType();
    }

    /**
     * Create an instance of {@link ChorDeploymentMessage }
     * 
     */
    public ChorDeploymentMessage createChorDeploymentMessage() {
        return new ChorDeploymentMessage();
    }

    /**
     * Create an instance of {@link IterateChorInstanceMessage }
     * 
     */
    public IterateChorInstanceMessage createIterateChorInstanceMessage() {
        return new IterateChorInstanceMessage();
    }

    /**
     * Create an instance of {@link ChorStartMessage }
     * 
     */
    public ChorStartMessage createChorStartMessage() {
        return new ChorStartMessage();
    }

    /**
     * Create an instance of {@link EndpointDataType }
     * 
     */
    public EndpointDataType createEndpointDataType() {
        return new EndpointDataType();
    }

    /**
     * Create an instance of {@link CurrentStateType }
     * 
     */
    public CurrentStateType createCurrentStateType() {
        return new CurrentStateType();
    }

    /**
     * Create an instance of {@link GetChorInstanceHistoryReturnMessage }
     * 
     */
    public GetChorInstanceHistoryReturnMessage createGetChorInstanceHistoryReturnMessage() {
        return new GetChorInstanceHistoryReturnMessage();
    }

    /**
     * Create an instance of {@link ProcessInstanceInformation }
     * 
     */
    public ProcessInstanceInformation createProcessInstanceInformation() {
        return new ProcessInstanceInformation();
    }

    /**
     * Create an instance of {@link ProcessBundleResultType }
     * 
     */
    public ProcessBundleResultType createProcessBundleResultType() {
        return new ProcessBundleResultType();
    }

    /**
     * Create an instance of {@link ChoreographyBundleResultType }
     * 
     */
    public ChoreographyBundleResultType createChoreographyBundleResultType() {
        return new ChoreographyBundleResultType();
    }

    /**
     * Create an instance of {@link ChorDeploymentEventMessage }
     * 
     */
    public ChorDeploymentEventMessage createChorDeploymentEventMessage() {
        return new ChorDeploymentEventMessage();
    }

    /**
     * Create an instance of {@link ChorProcessModelsInformationType }
     * 
     */
    public ChorProcessModelsInformationType createChorProcessModelsInformationType() {
        return new ChorProcessModelsInformationType();
    }

    /**
     * Create an instance of {@link ChorInstanceInformation }
     * 
     */
    public ChorInstanceInformation createChorInstanceInformation() {
        return new ChorInstanceInformation();
    }

    /**
     * Create an instance of {@link ProcessBundleType }
     * 
     */
    public ProcessBundleType createProcessBundleType() {
        return new ProcessBundleType();
    }

    /**
     * Create an instance of {@link ChorUndeploymentEventMessage }
     * 
     */
    public ChorUndeploymentEventMessage createChorUndeploymentEventMessage() {
        return new ChorUndeploymentEventMessage();
    }

    /**
     * Create an instance of {@link GetProcessInstanceHistoryMessage }
     * 
     */
    public GetProcessInstanceHistoryMessage createGetProcessInstanceHistoryMessage() {
        return new GetProcessInstanceHistoryMessage();
    }

    /**
     * Create an instance of {@link ChorIterationControlMessage }
     * 
     */
    public ChorIterationControlMessage createChorIterationControlMessage() {
        return new ChorIterationControlMessage();
    }

    /**
     * Create an instance of {@link GetChorInstancesReturnMessage }
     * 
     */
    public GetChorInstancesReturnMessage createGetChorInstancesReturnMessage() {
        return new GetChorInstancesReturnMessage();
    }

    /**
     * Create an instance of {@link ChoreographyBundleType }
     * 
     */
    public ChoreographyBundleType createChoreographyBundleType() {
        return new ChoreographyBundleType();
    }

    /**
     * Create an instance of {@link ChorProcessModelType }
     * 
     */
    public ChorProcessModelType createChorProcessModelType() {
        return new ChorProcessModelType();
    }

    /**
     * Create an instance of {@link GetChorInstancesMessage }
     * 
     */
    public GetChorInstancesMessage createGetChorInstancesMessage() {
        return new GetChorInstancesMessage();
    }

    /**
     * Create an instance of {@link ChorStartReturnMessage }
     * 
     */
    public ChorStartReturnMessage createChorStartReturnMessage() {
        return new ChorStartReturnMessage();
    }

    /**
     * Create an instance of {@link GetSnapshotVariablesMessage }
     * 
     */
    public GetSnapshotVariablesMessage createGetSnapshotVariablesMessage() {
        return new GetSnapshotVariablesMessage();
    }

    /**
     * Create an instance of {@link StartParticipantType }
     * 
     */
    public StartParticipantType createStartParticipantType() {
        return new StartParticipantType();
    }

    /**
     * Create an instance of {@link GetChorModelsReturnMessage }
     * 
     */
    public GetChorModelsReturnMessage createGetChorModelsReturnMessage() {
        return new GetChorModelsReturnMessage();
    }

    /**
     * Create an instance of {@link ProcessInstanceHistoryOfChorInstance }
     * 
     */
    public ProcessInstanceHistoryOfChorInstance createProcessInstanceHistoryOfChorInstance() {
        return new ProcessInstanceHistoryOfChorInstance();
    }

    /**
     * Create an instance of {@link ChorModelType }
     * 
     */
    public ChorModelType createChorModelType() {
        return new ChorModelType();
    }

    /**
     * Create an instance of {@link EventType }
     * 
     */
    public EventType createEventType() {
        return new EventType();
    }

    /**
     * Create an instance of {@link GetChorModelsMessage }
     * 
     */
    public GetChorModelsMessage createGetChorModelsMessage() {
        return new GetChorModelsMessage();
    }

    /**
     * Create an instance of {@link CorrelationType }
     * 
     */
    public CorrelationType createCorrelationType() {
        return new CorrelationType();
    }

    /**
     * Create an instance of {@link MessageLinkInstanceInformation }
     * 
     */
    public MessageLinkInstanceInformation createMessageLinkInstanceInformation() {
        return new MessageLinkInstanceInformation();
    }

    /**
     * Create an instance of {@link ServiceType }
     * 
     */
    public ServiceType createServiceType() {
        return new ServiceType();
    }

    /**
     * Create an instance of {@link CorrelationSetType }
     * 
     */
    public CorrelationSetType createCorrelationSetType() {
        return new CorrelationSetType();
    }

    /**
     * Create an instance of {@link GetSnapshotsMessage }
     * 
     */
    public GetSnapshotsMessage createGetSnapshotsMessage() {
        return new GetSnapshotsMessage();
    }

    /**
     * Create an instance of {@link GetProcessInstancesReturnMessage }
     * 
     */
    public GetProcessInstancesReturnMessage createGetProcessInstancesReturnMessage() {
        return new GetProcessInstancesReturnMessage();
    }

    /**
     * Create an instance of {@link ChorUndeploymentMessage }
     * 
     */
    public ChorUndeploymentMessage createChorUndeploymentMessage() {
        return new ChorUndeploymentMessage();
    }

    /**
     * Create an instance of {@link GetProcessInstancesMessage }
     * 
     */
    public GetProcessInstancesMessage createGetProcessInstancesMessage() {
        return new GetProcessInstancesMessage();
    }

    /**
     * Create an instance of {@link ChorControlMessage }
     * 
     */
    public ChorControlMessage createChorControlMessage() {
        return new ChorControlMessage();
    }

    /**
     * Create an instance of {@link ChorDeploymentResultMessage }
     * 
     */
    public ChorDeploymentResultMessage createChorDeploymentResultMessage() {
        return new ChorDeploymentResultMessage();
    }

    /**
     * Create an instance of {@link GetProcessInstanceHistoryReturnMessage }
     * 
     */
    public GetProcessInstanceHistoryReturnMessage createGetProcessInstanceHistoryReturnMessage() {
        return new GetProcessInstanceHistoryReturnMessage();
    }

    /**
     * Create an instance of {@link GetChorInstanceHistoryMessage }
     * 
     */
    public GetChorInstanceHistoryMessage createGetChorInstanceHistoryMessage() {
        return new GetChorInstanceHistoryMessage();
    }

    /**
     * Create an instance of {@link ChorBreakpointsRegisteredEventMessage }
     * 
     */
    public ChorBreakpointsRegisteredEventMessage createChorBreakpointsRegisteredEventMessage() {
        return new ChorBreakpointsRegisteredEventMessage();
    }

}
