//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.23 at 12:01:31 PM MESZ 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.example.org/choreography_instance_information_message", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package de.unistuttgart.iaas.chor.messages;
