//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.08 at 10:45:27 PM MEZ 
//


package de.unistuttgart.iaas.chor.messages;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.namespace.QName;


/**
 * <p>Java class for processBundleType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="processBundleType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="processModelID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}QName"/>
 *         &lt;element name="processFileName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="processArtifactWSDL" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="processFolderZip" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/>
 *         &lt;element name="deployed" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="correlationInformation" type="{http://www.example.org/choreography_deployment_message}correlationSetType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="endpoint" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="inboundServices" type="{http://www.example.org/choreography_deployment_message}serviceType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "processBundleType", namespace = "http://www.example.org/choreography_deployment_message", propOrder = {
    "processModelID",
    "name",
    "processFileName",
    "processArtifactWSDL",
    "processFolderZip",
    "deployed",
    "correlationInformation",
    "endpoint",
    "inboundServices"
})
public class ProcessBundleType {

    @XmlElement(required = true)
    protected String processModelID;
    @XmlElement(required = true)
    protected QName name;
    @XmlElement(required = true)
    protected String processFileName;
    @XmlElement(required = true)
    protected String processArtifactWSDL;
    @XmlElement(required = true)
    protected byte[] processFolderZip;
    protected Boolean deployed;
    protected List<CorrelationSetType> correlationInformation;
    protected List<String> endpoint;
    protected List<ServiceType> inboundServices;

    /**
     * Gets the value of the processModelID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProcessModelID() {
        return processModelID;
    }

    /**
     * Sets the value of the processModelID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProcessModelID(String value) {
        this.processModelID = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link QName }
     *     
     */
    public QName getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link QName }
     *     
     */
    public void setName(QName value) {
        this.name = value;
    }

    /**
     * Gets the value of the processFileName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProcessFileName() {
        return processFileName;
    }

    /**
     * Sets the value of the processFileName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProcessFileName(String value) {
        this.processFileName = value;
    }

    /**
     * Gets the value of the processArtifactWSDL property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProcessArtifactWSDL() {
        return processArtifactWSDL;
    }

    /**
     * Sets the value of the processArtifactWSDL property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProcessArtifactWSDL(String value) {
        this.processArtifactWSDL = value;
    }

    /**
     * Gets the value of the processFolderZip property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getProcessFolderZip() {
        return processFolderZip;
    }

    /**
     * Sets the value of the processFolderZip property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setProcessFolderZip(byte[] value) {
        this.processFolderZip = ((byte[]) value);
    }

    /**
     * Gets the value of the deployed property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDeployed() {
        return deployed;
    }

    /**
     * Sets the value of the deployed property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDeployed(Boolean value) {
        this.deployed = value;
    }

    /**
     * Gets the value of the correlationInformation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the correlationInformation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCorrelationInformation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CorrelationSetType }
     * 
     * 
     */
    public List<CorrelationSetType> getCorrelationInformation() {
        if (correlationInformation == null) {
            correlationInformation = new ArrayList<CorrelationSetType>();
        }
        return this.correlationInformation;
    }

    /**
     * Gets the value of the endpoint property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the endpoint property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEndpoint().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getEndpoint() {
        if (endpoint == null) {
            endpoint = new ArrayList<String>();
        }
        return this.endpoint;
    }

    /**
     * Gets the value of the inboundServices property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the inboundServices property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInboundServices().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ServiceType }
     * 
     * 
     */
    public List<ServiceType> getInboundServices() {
        if (inboundServices == null) {
            inboundServices = new ArrayList<ServiceType>();
        }
        return this.inboundServices;
    }

}
