//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.23 at 12:01:31 PM MESZ 
//


package de.unistuttgart.iaas.chor.messages;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.namespace.QName;


/**
 * <p>Java class for ProcessInstanceInformation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ProcessInstanceInformation">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="processInstanceID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="processModelID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="processName" type="{http://www.w3.org/2001/XMLSchema}QName"/>
 *         &lt;element name="packageName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="odeProcessInstanceID" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="choreographyInstanceID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="choreographyModelID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="choreographyModelName" type="{http://www.w3.org/2001/XMLSchema}QName"/>
 *         &lt;element name="state" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="version" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="timestamp" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ProcessInstanceInformation", propOrder = {
    "processInstanceID",
    "processModelID",
    "processName",
    "packageName",
    "odeProcessInstanceID",
    "choreographyInstanceID",
    "choreographyModelID",
    "choreographyModelName",
    "state",
    "version",
    "timestamp"
})
public class ProcessInstanceInformation {

    @XmlElement(required = true)
    protected String processInstanceID;
    @XmlElement(required = true)
    protected String processModelID;
    @XmlElement(required = true)
    protected QName processName;
    @XmlElement(required = true)
    protected String packageName;
    protected long odeProcessInstanceID;
    @XmlElement(required = true)
    protected String choreographyInstanceID;
    @XmlElement(required = true)
    protected String choreographyModelID;
    @XmlElement(required = true)
    protected QName choreographyModelName;
    @XmlElement(required = true)
    protected String state;
    protected long version;
    protected long timestamp;

    /**
     * Gets the value of the processInstanceID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProcessInstanceID() {
        return processInstanceID;
    }

    /**
     * Sets the value of the processInstanceID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProcessInstanceID(String value) {
        this.processInstanceID = value;
    }

    /**
     * Gets the value of the processModelID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProcessModelID() {
        return processModelID;
    }

    /**
     * Sets the value of the processModelID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProcessModelID(String value) {
        this.processModelID = value;
    }

    /**
     * Gets the value of the processName property.
     * 
     * @return
     *     possible object is
     *     {@link QName }
     *     
     */
    public QName getProcessName() {
        return processName;
    }

    /**
     * Sets the value of the processName property.
     * 
     * @param value
     *     allowed object is
     *     {@link QName }
     *     
     */
    public void setProcessName(QName value) {
        this.processName = value;
    }

    /**
     * Gets the value of the packageName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPackageName() {
        return packageName;
    }

    /**
     * Sets the value of the packageName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPackageName(String value) {
        this.packageName = value;
    }

    /**
     * Gets the value of the odeProcessInstanceID property.
     * 
     */
    public long getOdeProcessInstanceID() {
        return odeProcessInstanceID;
    }

    /**
     * Sets the value of the odeProcessInstanceID property.
     * 
     */
    public void setOdeProcessInstanceID(long value) {
        this.odeProcessInstanceID = value;
    }

    /**
     * Gets the value of the choreographyInstanceID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChoreographyInstanceID() {
        return choreographyInstanceID;
    }

    /**
     * Sets the value of the choreographyInstanceID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChoreographyInstanceID(String value) {
        this.choreographyInstanceID = value;
    }

    /**
     * Gets the value of the choreographyModelID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChoreographyModelID() {
        return choreographyModelID;
    }

    /**
     * Sets the value of the choreographyModelID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChoreographyModelID(String value) {
        this.choreographyModelID = value;
    }

    /**
     * Gets the value of the choreographyModelName property.
     * 
     * @return
     *     possible object is
     *     {@link QName }
     *     
     */
    public QName getChoreographyModelName() {
        return choreographyModelName;
    }

    /**
     * Sets the value of the choreographyModelName property.
     * 
     * @param value
     *     allowed object is
     *     {@link QName }
     *     
     */
    public void setChoreographyModelName(QName value) {
        this.choreographyModelName = value;
    }

    /**
     * Gets the value of the state property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getState() {
        return state;
    }

    /**
     * Sets the value of the state property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setState(String value) {
        this.state = value;
    }

    /**
     * Gets the value of the version property.
     * 
     */
    public long getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     */
    public void setVersion(long value) {
        this.version = value;
    }

    /**
     * Gets the value of the timestamp property.
     * 
     */
    public long getTimestamp() {
        return timestamp;
    }

    /**
     * Sets the value of the timestamp property.
     * 
     */
    public void setTimestamp(long value) {
        this.timestamp = value;
    }

}
