package org.apache.ode.deployapi;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.0.9
 * 2017-10-23T12:01:30.432+02:00
 * Generated source version: 3.0.9
 * 
 */
@WebService(targetNamespace = "http://www.apache.org/ode/deployapi", name = "DeploymentPortType")
@XmlSeeAlso({org.w3._2005._05.xmlmime.ObjectFactory.class, ObjectFactory.class})
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface DeploymentPortType {

    @WebResult(name = "processIds", targetNamespace = "http://www.apache.org/ode/deployapi", partName = "processIds")
    @WebMethod
    public ProcessIds listProcesses(
        @WebParam(partName = "packageName", name = "packageName")
        java.lang.String packageName
    );

    @WebResult(name = "response", targetNamespace = "http://www.apache.org/ode/deployapi", partName = "response")
    @WebMethod
    public DeployUnit deploy(
        @WebParam(partName = "name", name = "name")
        java.lang.String name,
        @WebParam(partName = "modelId", name = "modelId")
        java.lang.String modelId,
        @WebParam(partName = "package", name = "package")
        Package _package
    );

    @WebResult(name = "package", targetNamespace = "http://www.apache.org/ode/deployapi", partName = "package")
    @WebMethod(action = "http://www.apache.org/ode/deployapi/getDeploymentBundle")
    public Package getDeploymentBundle(
        @WebParam(partName = "packageName", name = "packageName")
        javax.xml.namespace.QName packageName
    );

    @WebResult(name = "response", targetNamespace = "http://www.apache.org/ode/deployapi", partName = "response")
    @WebMethod
    public boolean undeploy(
        @WebParam(partName = "packageName", name = "packageName")
        javax.xml.namespace.QName packageName
    );

    @WebResult(name = "deployedPackages", targetNamespace = "http://www.apache.org/ode/deployapi", partName = "deployedPackages")
    @WebMethod
    public PackageNames listDeployedPackages();

    @WebResult(name = "response", targetNamespace = "http://www.apache.org/ode/deployapi", partName = "response")
    @WebMethod
    public DeployUnit deployNewVersion(
        @WebParam(partName = "name", name = "name")
        java.lang.String name,
        @WebParam(partName = "package", name = "package")
        Package _package,
        @WebParam(partName = "InstanceID", name = "InstanceID")
        long instanceID
    );

    @WebResult(name = "packageName", targetNamespace = "http://www.apache.org/ode/deployapi", partName = "packageName")
    @WebMethod
    public java.lang.String getProcessPackage(
        @WebParam(partName = "processName", name = "processName")
        javax.xml.namespace.QName processName
    );
}
